from src.constants import *
import os,sys

ROOT_DIR=ROOT_DIR_KEY
DATASET_PATH=os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)

RAW_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,current_time_stamp,
                           DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)


TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,current_time_stamp,
                             DATA_INGESTION_INGESTED_DATA_DIR_key,TRAIN_DATA_DIR_KEY)



TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,current_time_stamp,
                             DATA_INGESTION_INGESTED_DATA_DIR_key,TEST_DATA_DIR_KEY)


# data transformation steps
PREPROCESSING_OBJ_FILE=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                    DATA_PROCESSOR_DIR,DATA_TRANSFORMATION_PROCESSOR_OBJ)

TRANSFORM_TRAIN_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                       DATA_TRANSFORMATION_DIR,TRANSFORAMTION_TRAIN_DATA_DIR)


TRANSFORM_TEST_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                       DATA_TRANSFORMATION_DIR,TRANSFORAMTION_TEST_DATA_DIR)

FEATURE_ENG_OBJ_FILE=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                    DATA_PROCESSOR_DIR,'processor.pkl')

MODEL_FILE_PATH=os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,MODEL_TRAINER_KEY,MODEL_OBJECT)
 